### ISSUE TITLE
关于动态加载页面

### ISSUE THREAD

**Issue by pangwu86** [zozoh/walnut#10]
有些项目, 需要实时的通过ajax等读取某些页面然后嵌入到当前页面中

目前项目推荐的页面存放位置是WEB-INF下, 也就是不能通过get("/xxx/xxx.jsp")这种方法读取

如果是放在WebContent下是可以读到, 但是就造成了页面会放在不同的位置, 写引用依赖的rs可能就比较麻烦,  jsp页面是都可以写${rs}来引用, 但是如果是一个html页面, 放在不同位置时写起来就不一样了

希望walnut给出一个接口,  比如 /page/.............. 就尝试读取 WEB-INF/page/.............

这样所有页面就都可以放在WEB-INF下了

**Comment by zozoh** [comment]
1. 希望 walnut 的扩展方式，是写 app，以及通过 httpapi, 还有 /gu/xxxxx 的方式
就是说，一个 HTML 页面的话，希望放到 WnIo 里，然后被读取，而不是放到 WEB-INF/xxx，总之忘记 WEB-INF 吧，希望你所有的自动以内容都能放到 WnIo 里，这样才能称作一个 “计算机” 么
2. 如果实在希望这么做，可以在自己的项目里，加入自己的 Module 哦。

**Comment by pangwu86** [comment]
如果是个jsp页面, 你放到WnIo里不行吧

**Comment by pangwu86** [comment]
还有就是放到WnIo里, 好像开发的时候不太友好

1. WnIo的实际文件目前是放在某个目录中而非项目的git库
2. WnIo文件的存放方式不是把相关文件放一个目录里,  你本地开发怎么搞?

**Comment by zozoh** [comment]
我们会在 walnut 支持 git
即，你的一个目录可以成为 git 库，你可以 git push/pull 的方式同步代码

**Comment by zozoh** [comment]
好像不需要继续跟踪了
