### ISSUE TITLE
ftp 服务，安全性的问题

### ISSUE THREAD

**Issue by zozoh** [zozoh/walnut#101]
考虑到 ftp 服务安全比较差，登录验证的时候，是不是不要输入用户名密码。
而是用户在 `.ftp` 目录下设置一个 `token` 之类的东东  ...

**Comment by zozoh** [comment]
Wendal~兽(389627265)  22:51:05
ftps可以吗
Wendal~兽(389627265)  22:53:01
带tls加密

**Comment by wendal** [comment]
"用 ftp 登录的时候不要用域的"   域的什么???

**Comment by zozoh** [comment]
域的用户名和密码

**Comment by wendal** [comment]
ftps需要生成密钥,然后过程比较繁琐,还没搞定.

c661e9db82e032a0c5507d794e066df648d0e7c3 已经完成token登录
