### ISSUE TITLE
adduser命令

### ISSUE THREAD

**Issue by pangwu86** [zozoh/walnut#109]
用户加入root组也无法创建用户，报错 e.io.forbidden

具体代码在这里
WnSecurityImpl中
![image](https://cloud.githubusercontent.com/assets/326471/21074308/d53b5896-bf30-11e6-8eff-451cfe05b572.png)

**Comment by zozoh** [comment]
改好了，只要是 root 组成员（不必是管理员，就不执行安全性检查）
