### ISSUE TITLE
form控件

### ISSUE THREAD

**Issue by pangwu86** [zozoh/walnut#110]
input类型 怎么设置placeholder字段

**Comment by zozoh** [comment]
在 UI 配置里面

```
placeholder :  "some text"
```

**Comment by pangwu86** [comment]
确定? 本地试了无效

![image](https://cloud.githubusercontent.com/assets/326471/21082247/9e979c36-c012-11e6-850e-f748822395d5.png)

这样写没错吧

**Comment by zozoh** [comment]
应该写在 `uiConf` 里面
