### ISSUE TITLE
writeMeta引发的问题

### ISSUE THREAD

**Issue by pangwu86** [zozoh/walnut#120]
在home下zhost13，包含属性 trumpet_place_name: 'tplace2'
root使用obj -match '{"d0":"home","trumpet_place_name":"tplace2"}' 可以正常查到
![image](https://cloud.githubusercontent.com/assets/326471/21799042/7df6236a-d752-11e6-9a12-332708eed404.png)

在java代码中，使用writeMate向zhost13写入一些meta，将trumpet_place_name给抹掉了
![image](https://cloud.githubusercontent.com/assets/326471/21799099/c45f8a76-d752-11e6-901b-2ba4ccee8993.png)

在命令行下，手动加回对应的数据，然后查询还是查不到
![image](https://cloud.githubusercontent.com/assets/326471/21799197/2fdc8682-d753-11e6-82cc-69f557bfad0f.png)

**Comment by zozoh** [comment]
干脆在 `org.nutz.walnut.impl.io.WnObjMetaOutputStream` 禁止掉 d0,d1 好了，靠

**Comment by zozoh** [comment]
@pangwu86  你看看如果搞定了就关闭吧
我整理了 Label 列表，记得有问题打标签
