### ISSUE TITLE
obj命令返回值问题

### ISSUE THREAD

**Issue by pangwu86** [zozoh/walnut#131]
执行一个类似这样的查询时 
obj -match "d0:'home',d1:'zhost7', pid:'vgnc4scb0qhicrlhmmpms5tr13', pcode:'68710703'"

之前版本返回一个空字符串，现在是返回null

代码定位到
cmds.java中的output_objs_as_json方法

![image](https://cloud.githubusercontent.com/assets/326471/22634148/308ff8f6-ec62-11e6-84cf-ac604fe51000.png)

这里主要是影响到jsc中调用obj查询返回判断时的一些问题，需要明确下没有值的返回值到底是什么

**Comment by zozoh** [comment]
因为 eval("null") 是可以的，但是 eval("") 好像就抛错

所以改成了 null
