### ISSUE TITLE
讨论 web socket

### ISSUE THREAD

**Issue by zozoh** [zozoh/walnut#136]
文档是 https://github.com/zozoh/walnut/blob/master/doc/core/websocket.md

**Comment by zozoh** [comment]
websocket 的话，会不会有消息收到一半的情况？

比如服务器推送:

```
{
    event : "hi",
    wsid  : "ojvnos2mjkhp1onk7ah8ra107t" 
}
```

客户端收到两条消息，分别是:

```
{
    event : "h
```

```
i",
    wsid  : "ojvnos2mjkhp1onk7ah8ra107t" 
}
```

**Comment by zozoh** [comment]
** wsid** 的问题，我倾向老方案（B）吧。 貌似更灵活一点。
方案A 有点暴力，使用场景会有限制吧

**Comment by wendal** [comment]
据我所知, websocket按帧传输, 收到FIN帧才代表数据片段结束,然后才触发onMessage

**Comment by zozoh** [comment]
哦，那我多虑了，哈 ^_^!

**Comment by pangwu86** [comment]
现在wendal做的那个就是方案B吧，方案A其实没啥好处吧

**Comment by wendal** [comment]
还有一种是room的方式

**Comment by zozoh** [comment]
决定了，用方案 B

**Comment by wendal** [comment]
io接口支持push/pop
