### ISSUE TITLE
hMaker : 提供 `dynamic` 控件替代原来的 `objlist/objshow` 的全部功能

### ISSUE THREAD

**Issue by zozoh** [zozoh/walnut#140]
- [x] 文档: `dynamic` 控件规范
- [x] 建立 `dynamic/prop` 的脚手架（从 DDS copy)
- [x] dynamic: 接口和模板的参数用 *form* 控件
- [x] dynamic: : 提供 `droplist` 列出所有可用 `thingset`
- [x] dynamic: : 提供 `droplist` 列出所有可用站点，默认是 `${siteName}` 表当前站点
- [x] dynamic: 提供 `droplist ` 控件
- [x] PageUI 提供根据控件类型获取控件列表的方法
- [x] 提供 `rs/ext/hmaker/hmc_dynamic` 支持上述修改
- [x] `com-dynamic` 完成渲染部分
- [x] 修改模板的 *jQuery* 控件，列表的要自己绘了
- [x] 参数部分支持 *required*
     + 文档
     + 解析 api.params 时候增加 required 字段
     + 属性面板显示
     + 提交请求的时候，required 参数为空拒绝提交
- [x] 在插入条上增加四个控件
- [x] 提供 `pager/pager_prop` 控件
- [x] 提供 `filter/filter_prop` 控件
- [x] 提供 `searcher/searcher_prop` 控件
- [x] 提供 `sorter/sorter_prop` 控件
- [x] 联调 `dynamic` 控件组
    + 支持 `*(xxx)@` 格式的参数配置，显示参数的可读名
    + 支持 `#<xxx>` 表示关联控件，值需要从控件里取 `getApiValue` 方法
    + 四个控件支持设置参数映射表
    + 在 `dynamic` 控件里面支持上述参数的修改

**Comment by wendal** [comment]
删掉了?

**Comment by zozoh** [comment]
暂时隐藏起来。不过原来gbox那些页面肯定是不再能工作了。
数据没问题
