### ISSUE TITLE
cmd_obj中match参数与searchUI的过滤条件导致的错误

### ISSUE THREAD

**Issue by pangwu86** [zozoh/walnut#144]
举例：需要查询一个目录下 alias不为空的数据
mongodb中写法为 {alias: {$ne: null}}
在console中可以写成 obj -match '{"alias":{"\\$ne":null}}'  // 需要加上一个反斜杠才行
在使用searchUI设置过滤条件时会遇到问题

```js
searchUI.uiFilter.setData({
      match: {"alias":{"\\$ne":null} }  // js语法，这里需要写两个反斜杠代表一个反斜杠
});

执行refresh时查询语句却变成了 obj -match '{"alias":{"\\$ne":null}}'  // 这里有2个反斜杠输出，导致查询出错
```

问题有2个问题

1. obj的match查询条件都要按照带\的方式来写吗？
2. searchUI这个应该是个bug

代码已提交，重现方式如下:
root用户登陆，命令行下执行open rootlogin, 点击图中按钮即可发现错误

![image](https://cloud.githubusercontent.com/assets/326471/23014922/e4a3c51e-f46b-11e6-9f35-e4055109eb14.png)

具体代码位置为 walnut项目 ROOT/app/wn.rootlogin/main.js 18行-28行

**Comment by zozoh** [comment]
增加了语法:

-  `alias="!"` 表示 `alias : {$ne:null}`
-  `alias="!xyz"` 表示 `alias : {$ne:"xyz"}`


另外，如果想构建一个控件时，添加 css，可以

```
var mainUI = new SearchUI({
    css : "theme/app/wn.rootlogin/main.css",
    $pel: $(document.body),
    ...
```

直接指定 css 段就好了

**Comment by pangwu86** [comment]
@zozoh 收到

**Comment by zozoh** [comment]
@pangwu86  记得 `css` 段要用 `theme` 开头，这样采用用到主题
