### ISSUE TITLE
浏览器加载 walnut 文件应该用到缓存

### ISSUE THREAD

**Issue by zozoh** [zozoh/walnut#151]
下面几个地方

- `/o/read`
- `/a/load`
- `/gu`

是强制刷新的，应该输出的 header 里弄个 Etag 之类的，以便用到缓存

**Comment by wendal** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

**Comment by wendal** [comment]
还有 /theme哦, 已fix

**Comment by wendal** [comment]
etag 生成规则:

有 sha1 --     $sha1[0:6]-$len-$lm
无 sha1 --     F-$len-$lm

**Comment by zozoh** [comment]
嗯，应该是完美解决，不过有那个 `Material-Design-Iconic-Font.woff2` 在内存的问题，还需要在观察一下，暂时 reopen

**Comment by zozoh** [comment]
不管了，Issue 太多，先关了

**Comment by zozoh** [comment]
可能是这个问题:  http://stackoverflow.com/questions/28897237/font-rendering-in-chrome-woff2-after-load-font-family-doesnt-want-to-change
