### ISSUE TITLE
一个obj的类型有DIR, FILE, OBJ , 其中 FILE OBJ的差别是?

### ISSUE THREAD

**Issue by pangwu86** [zozoh/walnut#16]

**Comment by zozoh** [comment]
* DIR， 目录， 不能有内容，但是能有子
* FILE, 文件，可以有内容，不能有子
* OBJ，对象，可以有内容，可以有子

实际上我只是定义了 OBJ，但是一直没有用
原来想的是让 task , comment 这些用 OBJ
但是纠结再，我想让 WnIo 是一个纯文件系统，因此可能近期我会把 OBJ 这个类型删掉

**Comment by zozoh** [comment]
不要纠结了，现在就是 FILE 和 DIR
