### ISSUE TITLE
/gu/rs目录下的文件的第一次被访问时

### ISSUE THREAD

**Issue by pangwu86** [zozoh/walnut#17]
/gu/rs 一般是给页面用的,  被扫描到的话  c, m g 都是guest

但是如果一个用户在命令中进去到对应目录并ls的话, 就成了这个用户创建的

然后再访问这些文件的时候, 权限就不一样了

目前发现的bug是

比如这个目录 /rs/core/js/jquery/jquery-2.1.3

里面实际是3个文件
jquery-2.1.3.js
jquery-2.1.3.min.js
jquery-2.1.3.min.map

但是ls 只显示2个

count可以看到是3个

**Comment by pangwu86** [comment]
[root@strato.home jquery-2.1.3]# pwd
/rs/core/js/jquery/jquery-2.1.3
[root@strato.home jquery-2.1.3]# ls
jquery-2.1.3.js
jquery-2.1.3.min.map
[root@strato.home jquery-2.1.3]# count
3

**Comment by pangwu86** [comment]
具体原因就是所属grp不一样,  昨天定位到代码的那一行了, 等me再找下

**Comment by zozoh** [comment]
嗯，那个是个缺陷，稍后我来修正吧

**Comment by zozoh** [comment]
添加了 JUnit :

```java
public abstract class AbstractWnIoTest extends BaseIoTest {

    @Test
    public void test_mount_local_auto_use_root_cgm() {
        ...

```
