### ISSUE TITLE
AppModule中的run方法

### ISSUE THREAD

**Issue by pangwu86** [zozoh/walnut#18]
@At("/run/?/**")
    @Ok("void")
    public void run(String appName,
                    String mimeType,
                    HttpServletRequest req,
                    HttpServletResponse resp) throws IOException {

这个方法的appName 没有用吧  写啥都行  反正只要后面的命令对了就行

/run/wn.console?ls
/run/test.hahaha?ls

是一样的结果

**Comment by zozoh** [comment]
留着以后用的， 考虑到 app 可能会提供一点自己独有的命令 ...

**Comment by zozoh** [comment]
还是有用的，比如 APP_HOME 环境变量等
