### ISSUE TITLE
讨论：关于底层机制修改引发的bug

### ISSUE THREAD

**Issue by pangwu86** [zozoh/walnut#186]
比如之前cmd中obj关于空对象的返回值问题，由空字符串改为“null”
今天测试wnml的一个网页，在cmd_wnml被重构后就挂掉了

应该说是缺乏测试用例导致的吧，但补全测试用例又不是那么容易

讨论下再出现类似问题怎么能尽量避免或者说怎么能通知到使用该命令的人去第一时间关注下相关修改

**Comment by zozoh** [comment]
现在还在代码激进修改状态，好像不太好避免

**Comment by zozoh** [comment]
还是应该逐渐用 JUnit 把逻辑固定住

**Comment by zozoh** [comment]
以后所有的修改，必须有 Issue 记录，并有里程碑管理

**Comment by zozoh** [comment]
应该就这样
