### ISSUE TITLE
什么情况添加obj 什么情况添加tree

### ISSUE THREAD

**Issue by pangwu86** [zozoh/walnut#19]

**Comment by zozoh** [comment]
没懂你的问题？ 你不能添加 tree 吧

**Comment by pangwu86** [comment]
就是me观察 db.tree 中的数量 少于 db.obj 的数量

**Comment by pangwu86** [comment]
手动新建一个文件的时候,  tree obj 都会+1

**Comment by zozoh** [comment]
* tree 记录文件的层级关系
* obj 记录对象的元数据
* tree 现在有两个实现，`MongoTree` 和 `LocaleTree`
* `MongoTree` 记录在 `db.tree` 里
* `LocalTree` 就是对应本地文件夹
* 因此你会发现 obj 比 tree 内容多，因为还记录了本地文件的元数据

**Comment by pangwu86** [comment]
me写了个命令 count  统计某个目录下的文件数量,  添加了个过滤功能

结果发现是tree里面查找的, 然后里面没有tp这个属性
