### ISSUE TITLE
求补充MaskUI的文档

### ISSUE THREAD

**Issue by pangwu86** [zozoh/walnut#200]
https://github.com/zozoh/walnut/blob/master/doc/ui/core/mask.md

写的太少了，尝试各种方法都报错，各种坑

**Comment by pangwu86** [comment]
例如：在render中this.$main.html('.........')
如果在插入的html中使用gasket的方式，会报错说找不到对应的gasket，貌似是需要在加入时做了一些处理才行

如果改成直接在配置的dom使用上面的html，又因为不符合maskUI现有html的结构导致报错

还有setup怎么用，在render中怎么调用都没有具体的讲解，特别是render中this里隐藏的各种神奇的熟悉

**Comment by zozoh** [comment]
哦，我的惯例，$xxx 基本代表一个 jQuery 对象

总之，我应该升级一下文档哦

setup 配置项的 uiType 是一个 UI 的类型， uiConf 是这个 UI 配置项
mask 被 render 的时候，会先 render 这个 UI

之后在运行时(render以后），调用 mask 的 this.body 就是这个 setup 配置的 UI 实例了
