### ISSUE TITLE
缩略图的初始化以及获取逻辑能不能支持任意尺寸

### ISSUE THREAD

**Issue by zozoh** [zozoh/walnut#33]
现在缩略图服务只支持几种固定尺寸，当系统被多个开发者使用的时候，有些开发者
1. 如果获取缩略图的时候，给定尺寸文件不存在，如能能生成一张，就能支持各种缩略图的大小
2. 而且在 WnSetup 里就不用 copy 所有尺寸的缩略图

缺点是，可能会导致生成很多缩略图文件。可以再附加策略
1. 系统给定几个标准尺寸，符合标准尺寸的缩略图一经生成则会一直存在
2. 如果不符合标准尺寸，用 expi 元数据指定过期时间，一旦过期，系统会自动删除的
3. 某个非标准尺寸如果多次被用到，应该记成标准尺寸
4. 标准尺寸列表应该记录在 /etc/thumbnail.conf 里是一个 json 文件

```
----------------------  /etc/thumbnail.conf 的内容 ----------------------
{
    stdsz : ["256x256", "128x128", "64x64", "32x32", "24x24", "16x16"],
    expi  : 3600   // 非标准尺寸，缓存多少秒
    add_ threshold : 0,  // 非标准尺寸请求多少次以后会变成标准尺寸， 0 表示永远不
}
```

**Comment by pangwu86** [comment]
1. "WnSetup 里 copy所有尺寸的缩略图", 其实是只拷贝一张, 然后自动生成其他尺寸. 不过更好处理方式是将这个操作包装成一个命令, 这样随时可以替换默认的缩率图,  而不非只有服务启动时, 不过启动时判断下是否有新缩略图要用也是ok的
2. 非标准的如果比原图大?  相当于放大了, 肯定会会造成模糊,  这种有必要生成吗?
3. 非标准, 应该设定个范围, [512, 16],  过大或过小都可能生成了也没有意义
4. 多次用到的情况, 要把这个尺寸记在哪里? 是针对这一张图还是针对全部图片, 记录为标准尺寸

**Comment by zozoh** [comment]
文档 https://github.com/zozoh/walnut/blob/master/doc/core/preview.md
 有乱码吧

**Comment by zozoh** [comment]
缩略图也没啥可改的咯
