### ISSUE TITLE
WnIo 考虑加个truncate方法不?

### ISSUE THREAD

**Issue by wendal** [zozoh/walnut#34]
io.truncate(WnObj obj, int size)

其中size是目标大小

**Comment by zozoh** [comment]
是用来 copy 的？ 还是打算用来干嘛？

**Comment by wendal** [comment]
将文件变成指定大小

**Comment by pangwu86** [comment]
剪裁? 变大?

**Comment by zozoh** [comment]
应该是大约这样吧：
```java
io.truncate(WnObj o, long off, long len);
```
厄，提供一个咯，不过什么时候会需要将文件截断到指定大小呢？  log ?

**Comment by zozoh** [comment]
@wendal 说 FUSE 会用到

**Comment by zozoh** [comment]
这个和 #41 一起考虑，看来还是需要把 WnStore 接口重构一下，或者这部分换成其他的接口
需要支持 :

1. 句柄式操作, 即 open 一个句柄，然后随便读写
2. 保存的时候更新到对应的持久化介质里

嗯 ... 蛮大的改动的

**Comment by zozoh** [comment]
先添加一个策略文档吧:  https://github.com/zozoh/walnut/blob/master/doc/core/storage.md

**Comment by wendal** [comment]
额,为啥这个issue是ASAP呢?

**Comment by zozoh** [comment]
因为我想在第一个里程碑前搞定它
原因是，第一个里程碑后，就准备生产数据了 ...

**Comment by wendal** [comment]
已经ok了

**Comment by zozoh** [comment]
嗯，那我关了哦
