### ISSUE TITLE
ZUI 不通过 Mod 发 exec 

### ISSUE THREAD

**Issue by zozoh** [zozoh/walnut#36]
1. 原来的想法是， zui 能独立于 walnut，所以把 exec 等放到 mod 里了
2. 不过现在看起来， zui 不能独立于 walnut，或者说，独立了木啥意义
3. 某些界面，如果想独立，还是抽象出一个 jquery 插件来的爽快
4. 因此 exec 应该由 zui 提供比较好, 或者起码是一个帮助函数，不能是 Backbone.Model

@pangwu86  你怎么看？

**Comment by pangwu86** [comment]
或者干脆把命令执行跟数据返回机制独立出来,  相当于一个ajax.post这样的一个方法,  这样ui层怎么写都行 只要遵守exec的规范

**Comment by pangwu86** [comment]
现在walnut的三个js的主要功能
```
walnut.js            命令执行与返回, 是与cmd相关的
walnut.obj.js      保存对象, 跟写入对象,  其实是跟obj相关的
walnut.client.js   记录执行命令的历史, 无后台交互, 仅仅是前端记录
```

**Comment by pangwu86** [comment]
关于zui是不是能独立的问题, 其实是看zui的定位.

zui目前解决了 模板, 自适应, ui嵌套等问题.  

但缺乏合适的实例与文档, 至少me现在用起来的不很顺手, 

比如一个功能, 不知道zui里是不是实现了, 规则也不清楚怎么配置, 只有去看现有的例子, 但现有的例子又不一定是针对那个想要的功能去写的, 所以只有看zui代码的实现, 这就造成了了使用上的困难, 所以有时候, 直接自己实现比用zui来的快也更容易改.

所以zui要独立, me觉得解决好例子跟文档就可以了.

**Comment by zozoh** [comment]
嗯，那就:

1. walnut.js 三个 js 合并成一个 JS
2. 让 walnut.js 和 backbone 无关

zui 的文档啥的，我继续补充吧，简单的说，提供的功能包括:

1. 自适应 (resize + ui-fitparent)
2. UI 的快捷键支持，比如帮你捕捉 Esc 等按键
3. html 模板
4. 本地化字符串支持
5. 扩展点 (ui-gasket) 构建子 UI 的树结构，操作父节点的 resize,inti,destroy 会向下传播
6. 基于 sea.js，是一个 Backbone 的 View
7. 代码模板功能 (UI.ccode)

基本就这些了，具体的使用如果感觉诡异，随时找我喔

我会尽快补文档，现在的文档就是 zui.js 开头那段 ...

**Comment by pangwu86** [comment]
例子也很重要, 各个参数的配置效果, 写个专门的demo页最好了

那天使用嵌套, 之前的代码里只有upload那是嵌套, 那块一开始没搞清gasket是咋用的, 名字是要设定哈
结果换了个方式没有用gaeket也成功调用起来了, 但是只有第一次ok, 后面再调用, 嵌套的内部ui总是无法resize

后来仔细查了下, 明白了的gasket的用法, 但一开始能调用起来的代码也暴露出来问题

主要是require.async, 如果是第一次读取, 就是异步的, 但是第二次发现已经读过了, 就成了同步的. 这就造成了嵌套UI的调用次序问题

虽然现在的gasket用法, 最后效果是正常的, 因为在最后调用最外层的resize(然后依次调用内部UI的resize),  但是在这之前的过程中会优先初始化内部UI, 也都调用一遍resize(这时候最外面的UI的大小基本都是100%,0) 其实就是多了一些无意义的重复调用.  这个应该还是代码的上逻辑问题

**Comment by zozoh** [comment]
???  你是说初始化的时候，会重复调用子 UI 的 resize ?

**Comment by pangwu86** [comment]
对的,  从第二次调用的开始, 执行顺序就不一样了.  会先跑一边子UI的resize, 最后再调用最外层的resize(根据gasket就把子UI的resize又调了一边)

**Comment by zozoh** [comment]
每个 UI 都会从 ZUI 继承了 `exec` 方法:

```
/*................................................................
# 执行命令的 options 是一组回调
{
    // 当得到返回的回调
    msgShow  : function(line){..}    // 显示一行输出
    msgError : function(line){..}    // 显示一行错误输出
    msgEnd   : function(){..}        // 表示不会再有输出了
    // 请求完毕的回调
    complete : function(content){..}     // 全部执行完
    done     : function(content){..}     // 执行成功
    fail     : function(Content){..}     // 执行失败
}
如果仅仅是一个函数，那么相当于
{
    complate : function(content){..}
}
*/
exec: function (str, options) {
```

使用的例子，比如:

```
// 仅仅是给一个命令执行完的回调
UI.exec("obj *", function () {
    // TODO 命令执行完的操作
});

// 更多的定制
UI.exec("obj * -json", {
    msgShow  : function(line){..},
    msgError : function(line){..},
    msgEnd   : function(line){..},
    done     : function () {
        // TODO 命令执行完的操作
    }
});
```
