### ISSUE TITLE
WnIo.getRealPath 需要删除

### ISSUE THREAD

**Issue by zozoh** [zozoh/walnut#42]
1. 因为 IO 对应的文件内容，根据不通的实现类，可以保存在不只是本地磁盘上
2. 如果提供了这个函数，那么 Io 的 Store 就不可能扩展做分布式了

如果是视频转换等服务，现在，只能是从 Io 里 copy 一份内容出来，而不应该直接找到存储的 SHA1 来直接操作

**Comment by pangwu86** [comment]
视频转换服务copy一份视频再处理的的话, 如果视频特别大, copy既浪费空间又浪费时间

那就只针对strato2实现一个好了, 把walnut的去掉

**Comment by pangwu86** [comment]
或者是 getRealPath 如果返回null, 表名无法获得具体磁盘地址, 这样让程序自己去处理后面的,  能拿到的就返回对应的真实地址

**Comment by zozoh** [comment]
从接口的角度，如果提供了 getRealPath 就破坏了封装性。 把对对象内容操作的具体方式暴露给调用者，内部实现一旦修改，很容易出问题喔

**Comment by pangwu86** [comment]
这次直接拿path的根本原因是 调用ffmpeg转换视频, 需要 -i 参数添加源文件的路径 

这种需求其实就是相当于walnut跟外部服务的对接上的问题, 其实将来很可能还会有类似的, copy出来的唯一问题就是牺牲了一部分时间与空间(文件越大也就是时间越长了), 不过想这种后台运行的, 慢一点倒也无妨, 空间么硬盘够大也无所谓了

那就从接口里删了吧, 改成copy出来搞

**Comment by wendal** [comment]
这正是fuse和dockerBox会解决的情况

**Comment by pangwu86** [comment]
嗯? 楼上的意思是?

**Comment by wendal** [comment]
转视频的两条件,   本地文件+本地二进制文件的运行

fuse将walnut映射为本地文件夹, 然后docker解决运行二进制程序的问题
