### ISSUE TITLE
console的输出

### ISSUE THREAD

**Issue by pangwu86** [zozoh/walnut#50]
在cmd中,
如果先执行sys.out.printxxx,  后执行sys.err.printxxx,  console中的文字颜色全部为白色
如果先执行sys.err.printxxx,  后执行sys.out.printxxx,  console中的文字颜色全部为红色

也就是先执行的那个输出会覆盖后面输出的颜色

**Comment by zozoh** [comment]
喔，这个是因为 Response 就一个 OutputStream
我是看错误流还是标准输出谁先抢到写入，来标记 http 的状态码
如果状态吗是 200 就是白的，否则就是红的

我想，之后做 WebSocket 版的，就应该能解决这个问题
现在就是标准 HTTP 请求，不好搞
