### ISSUE TITLE
权限不足时,io操作的提示不够友好

### ISSUE THREAD

**Issue by pangwu86** [zozoh/walnut#52]
![image](https://cloud.githubusercontent.com/assets/326471/11924865/b5488d40-a7f0-11e5-83c9-d881bfb95f5f.png)

/home/bjyb 目录下有个 roles目录, 但是是root创建的
使用byjb用户ls时看不到该目录, mkdir 提示该目录已经存在
但是提示只有io的错误, 无权限相关提示

**Comment by zozoh** [comment]
厄，否则怎么报？
ls 的时候不能报错吧。
创建的时候，报错的确就是 `e.io.obj.exists`  哦

**Comment by pangwu86** [comment]
能加上权限相关的提示吗?  
现在的提示可以推导出是权限的原因, 但是如果不用root看一眼的话 估计bjyb用户会蒙圈的, 怎么看不到的东西还创建不了呢

**Comment by zozoh** [comment]
嗯，我考虑下

**Comment by zozoh** [comment]
考虑到：用户没有权限知道这个对象是否是真正存在的
不改
