### ISSUE TITLE
#前端问题# theme文件的存放方式

### ISSUE THREAD

**Issue by pangwu86** [zozoh/walnut#68]
以hmaker为例

![image](https://cloud.githubusercontent.com/assets/326471/18229818/eeec9490-72b8-11e6-806a-a25a794712f7.png)

hmaker相关模板，js都在app/wn.hmaker2目录下，唯独css是放在theme中

![image](https://cloud.githubusercontent.com/assets/326471/18229824/0e8785ee-72b9-11e6-88e0-e6ba7e3f06fb.png)

theme真实目录是另一个目录中，跟当前目录中的没有关系

![image](https://cloud.githubusercontent.com/assets/326471/18229830/44fd08ba-72b9-11e6-8205-7a56be190026.png)

而像console，wedit等是直接放在控件目录中的

这样的问题就是

1. 一个控件的css放在哪里是怎样规定的？为什么要这样放？
2 theme是想着全局替换的话，那局部替换某个控件的css怎么做，new UI（{css：“另一个版本css”}）调用时指定吗？

**Comment by pangwu86** [comment]
theme/r 是配置在哪里的？没找到呢

**Comment by zozoh** [comment]
`org.nutz.walnut.web.module.ThemeModule`

基本思路是服务器收到 theme/r/xxx 请求，读取一下环境变量 `MY_THEME` 如果设置了从这个主题目录下找对应的 css，否则直接从 ui 所在目录下面找

**Comment by pangwu86** [comment]
@zozoh 第一个问题回答一下

还有，如果是写成app，就要放到theme下，如果是写控件就放到自己的目录下？ 这样用
