### ISSUE TITLE
#前端问题# app目录中文件存放

### ISSUE THREAD

**Issue by pangwu86** [zozoh/walnut#69]
![image](https://cloud.githubusercontent.com/assets/326471/18229840/bf8697ae-72b9-11e6-9cf9-67b3118bc77e.png)

wn.browser,wn.console,wn.wedit等，里面是main.js 也就是一个app的主文件

wn.hmaker wn.pvg, 里面是这个控件的定义文件

两种文件为啥要都放在app目录中?

wn.hmaker wn.pvg 不应该放在 ui目录（rs/core/js/ui）中吗？

**Comment by zozoh** [comment]
wn.hmaker 是个 app 哦，app 内部可以有自己的控件和css,i18n 等，是高内聚的
app 是依赖 walnut/util.js 的(Wn)，因为要处理和服务交互的数据
/rs/core/js/ui 里面放的是通用的 UI 控件，他们是不依赖 Wn 的

**Comment by pangwu86** [comment]
@zozoh 怎么样算是一个app呢？  wn.browser其实就是在main.js里调用了一下 ui中的obrowser这个控件

wn.hmaker2里面的代码更像是 obrowser 控件的定义，而不是一个调用？ 

所以这里疑问就是， 到底这个app里应该是怎么个写法 或者说 代码存放的位置到底是应该放在 app下 还是 ui里

**Comment by zozoh** [comment]
哦，那个wn.hmaker2 也应该提供一个吗 main 的，不过我还木写

一个 app 就是一个目录，包含一组 js/css/html/command ， 现在没有 command 的原因是我们。docker 还没整合好，所以命令部分我们都得写 Java 

如果你认为你的 js/css/html/command，其他 app 用不到，那么就放到自己的目录下，否则就放出来咯

**Comment by pangwu86** [comment]
那就是说放到app目录还是放到ui目录的标准是 “其他app是否用的到”？ 是否可以这么理解

**Comment by zozoh** [comment]
是
