### ISSUE TITLE
#前端问题# args语法问题

### ISSUE THREAD

**Issue by pangwu86** [zozoh/walnut#71]
![image](https://cloud.githubusercontent.com/assets/326471/18229862/ff240f1c-72ba-11e6-802c-538c43805f94.png)

1660行这里是异步的吧，

是不是会先执行下面的 callback.apply, 而这个时候的args还是空数组

**Comment by zozoh** [comment]
哦，不会，因为在 define 里面
seajs 的 require 只能写字面量，如果 deps 是数组，只能用 async 方法取，但是那时候已经加载到本地了，所以和同步效果一样

**Comment by pangwu86** [comment]
看明白了，真诡异
