### ISSUE TITLE
#前端问题# UI初始化的参数

### ISSUE THREAD

**Issue by pangwu86** [zozoh/walnut#72]
![image](https://cloud.githubusercontent.com/assets/326471/18229869/7038e8f8-72bb-11e6-96d7-70eb5ba40bf7.png)

exec: Wn.exec
app: Wn.app()

这两个基本上就是默认的，直接在父类中加个默认值吧

**Comment by pangwu86** [comment]
其他的参数有个提议

就是参数是否能分一下类，或者说不仅仅是初始化UI，还有新写一个控件

比如现在写一个控件
init:...
redraw:.....
on_redraw:.....
printA:.....
_do_something:....

各种类型的方法，参数都写在了同一层，能不能按照类型划分一下，这样写起来或者查找起来相对容易些

**Comment by pangwu86** [comment]
就是现在有对数据操作的方法，有对dom结构操作的方法，有一些内部辅助小方法，都写在了同一层上

没有命名规约的，没有归类的话，查找只能一个个往下翻

**Comment by zozoh** [comment]
我再 submit 上，是 `Command+P` 然后输入 `@` 就能看到函数列表

一个 UI 你声明的方法，会被 copy 到实例上，比如你声明了一个 UI

```
MyUI {
   ... 
  methodA : function() {
   }
   ...
}
```

当你 `var abc = new MyUI();` 的时候，你得到的实例是可以直接 `abc.methodA()` 的
如果你分成多个层，比如 

```
MyUI {
   ... 
   util : {
      methodA : function() {
      }
   }
   ...
}
```
你得到实例后，调用 `abc.util.methodA()`  那么你的方法的 `this` 就不是 `abc` 这个 UI 的实例了
也不能要求别人这么来调用 -> `abc.util.methodA.call(abc)`  更瘸。

而且一个方法的 `this` 总是保持为 UI 的实例本身，这个比较符合大家编程的直觉，也省掉很多麻烦。


实际上，当初设计 ZUI，我是把方法和属性分层放的，但是实际用起来很麻烦，就是我上面说的 this 的问题，很坑，后来干脆都一层，省心

来另，我用 sublime 写程序，没有代码折叠功能，所以一层很多层对我影响也不大 :P

**Comment by pangwu86** [comment]
@zozoh 

```js
MyUI {
   ... 
   util : {
      methodA : function() {
      }
   }
   ...
}

var abc = new MyUI();
abc.methodA() ;   //  这样用，其实是可以做到的，因为本身这个UI是ZUI.def出来的，可以做一点处理
```

代码分层主要是为了查问题的时候方便些，也没有说不分就不行，先这样吧
