### ISSUE TITLE
#前端问题# 什么情况下需要使用 keepDom : true

### ISSUE THREAD

**Issue by pangwu86** [zozoh/walnut#73]

**Comment by zozoh** [comment]
当这个 UI 可以被附着在一个已经有的 DOM 上的时候
你在 strato 项目里遇不到这个情况
在 hmaker(网页编辑器） 里，这个特性很有用

同时，如果 ZUI 被用在通常意义的网站前端，很多前端的人，喜欢给出一段 JS 代码，他对这段 JS 的 DOM 有一定要求，但是不太严格，CSS 和 i18n 啥的他统统不管
那么用 keepDom 为 true 的方式声明一个 ZUI 控件就是在合适不过的了

**Comment by pangwu86** [comment]
还是没懂什么情况下会用，能举个具体点的例子吗？ 或者等遇到再说也行，不过感觉应该是会绕开这种情况

**Comment by zozoh** [comment]
嗯，等你看到  hmaker 里面的代码，就知道了，现在暂时先无视吧
