### ISSUE TITLE
#前端问题# 参数名，方法名，有没有什么规律

### ISSUE THREAD

**Issue by pangwu86** [zozoh/walnut#74]
目录看到的代码中，大写的，小写的，大小写混合，带下划线的，带多个下划线的

有没有什么规约，看名称就能知道大概的作用是什么

**Comment by pangwu86** [comment]
$screen : UI.arena.find(".hmpg-screen")  // 一个jq对象


var opt = {
            uiName: uiName,
            tagName: 'div',
            className: uiName.replace(/[.]/g, '-'),
            $ui: {}    // 一个普通对象
        };

**Comment by pangwu86** [comment]
conf， opt， options

**Comment by zozoh** [comment]
我能想到的一些约定

- $xxx 基本是 jQuery 对象，如果是一个函数，那么一定返回一个 jQuery 对象
- conf 通常是读取的配置对象的本地变量名，文件对象我一般是  oConf， 
- opt 是 options 的简称，每个 UI 实例都有一个 options 成员变量，存储实例的配置信息
    - 敲码的时候觉得太长，后来我通常都在函数内用 opt 来指代它
- `__` 或者 `_` 和传统一样是表示不希望被人直接使用的私有方法，具体是一个 `_` 还是两个 `__` 主要看心情，如果特别不希望别人用，我通常用 `__`
- 驼峰命名的函数，是我希望 UI 开放给调用者调用的
- 下划线分隔命名的函数，是我不介意被人调用，但是我认为你没什么机会会调用到的函数
- 如果例外纯属笔误

**Comment by pangwu86** [comment]
最后一句大亮
