### ISSUE TITLE
#前端问题# actived 这个参数是干嘛用的？

### ISSUE THREAD

**Issue by pangwu86** [zozoh/walnut#75]
![14728946623694](https://cloud.githubusercontent.com/assets/326471/18229927/8c888cbe-72bd-11e6-82fa-147758a655bc.jpg)

**Comment by pangwu86** [comment]
为啥要设置为 yes

**Comment by wendal** [comment]
不要发截图啊...

**Comment by zozoh** [comment]
不要发截图 +1

**Comment by zozoh** [comment]
这个方法无视吧，我考虑稍后去掉
现在也基本没啥用
