### ISSUE TITLE
#前端问题# 加载i18n

### ISSUE THREAD

**Issue by pangwu86** [zozoh/walnut#76]
wn.browser中

	// 看看是不是要加载自定义的多国语言字符串
	var i18nStr = Wn.exec("appi18n " + window.$zui_i18n);
	if (!/^e[.]io/.test(i18nStr)) {
		i18n = $z.fromJson(i18nStr);
		_.extend(ZUI.g_msg_map, i18n);
	}

有这么一段加载后台i18n的代码，而且这个命令里的i18n文件位置是写死的，这样不太好吧

![image](https://cloud.githubusercontent.com/assets/326471/18229958/ea1bb854-72bf-11e6-8b8f-7a73c5520e2d.png)

再就是真的需要加载的话，也应该上面那个做个一个隐藏的内部调用的机制，不要在UI初始化时用户自己写吧，作成一个自动处理的方式

**Comment by zozoh** [comment]
嗯，这个路径弄成环境变量比较好
或者 obrowser 读取这个环境变量，如果有，就加载，而不需要 appi18n 这个命令了

**Comment by pangwu86** [comment]
坐等修正
