### ISSUE TITLE
#前端问题# 使用strato init命令，为啥出来的页面不一样

### ISSUE THREAD

**Issue by pangwu86** [zozoh/walnut#77]
cherry上的是这样

![image](https://cloud.githubusercontent.com/assets/326471/18230090/febc397e-72c3-11e6-8da0-f97dae67e139.png)

me本地是这样

![image](https://cloud.githubusercontent.com/assets/326471/18230092/09ff5b9a-72c4-11e6-85c6-0cb65df6a6da.png)

哪里没配置对吧

**Comment by wendal** [comment]
哈哈,这个我知道, 环境变量不一样

**Comment by zozoh** [comment]
还有，你的 `~/.ui` 要 link strato 下面的 UI
应该在 walnut 的文件系统的  `/rs/strato/ui` 目录下

```
rm ~/.ui
ln -s /rs/strato/ui ~/.ui
```

**Comment by pangwu86** [comment]
me好像找到原因了
