### ISSUE TITLE
#前端问题# 关于zui中使用vue的问题

### ISSUE THREAD

**Issue by pangwu86** [zozoh/walnut#80]
目前的遇到的主要是vue的模板与zui中i18n的使用上有冲突
语法都是{{xxx}}，需要讨论一下解决方案

**Comment by pangwu86** [comment]
发现这还只真是个问题，封装成jq插件或vue插件，跟zui的国家化如何整合的问题

**Comment by zozoh** [comment]
讨论的结果是：  jQuery 插件用配置，配置进去
好像没别的了

**Comment by zozoh** [comment]
好像没问题了
