### ISSUE TITLE
wjson 好像会有 JS Error

### ISSUE THREAD

**Issue by zozoh** [zozoh/walnut#88]
重现步骤
1. 弄一个 `{x:100,y:99}` 的 `test.json` 文件
2. 把 x 改成数组
3. 数组上点 “添加”

**Comment by pangwu86** [comment]
![image](https://cloud.githubusercontent.com/assets/326471/19407295/70fc4cbe-92d0-11e6-8b5d-c98edfb057ed.png)

你说的是这个错误吧，没找到原因来，不过这个不是vue的报错，应该是上一层zui封装时可能导致了啥错误

**Comment by zozoh** [comment]
在点添加的地方，一路打点 log 进去，最后看看传入的 jQuery 对象是啥

**Comment by zozoh** [comment]
我认为关键是，要花点时间看看 wjson 的用户体验设计问题
