### ISSUE TITLE
wjson 的已经有了菜单按钮条了，是不是添加/删除等放在上面会更好呢？

### ISSUE THREAD

**Issue by zozoh** [zozoh/walnut#89]
现在添加删除放在每个项目的首部，因为控件并没有显示当前编辑项，是为了实现上的便利。

如果从用户体验考虑，做如下修改:
1. 添加删除放在菜单条上
2. 可以高亮编辑项
3. 删除高亮项目会自动高亮下一个节点
4. 每项首部，图标根据项目的类型而不同，比如数组就显示一个 `[]` 的图标等

这样除了能保持现有的体验，还能额外得到下面的好处：
1.  用户可以很直觉的知道可以添加和删除，否则只有点到每个项目首部下拉菜单才能明白
2. 可以连续点添加添加添加
3. 可以连续点删除删除删除  
4. 这样的 JSON 对象会更加直观的看到每项的类型，给用户的信息更多

讨论一下？

**Comment by pangwu86** [comment]
1. 之前考虑加过，后来去掉了，觉得每次操作都要移动鼠标到上面有点怪

2. 有高亮
![image](https://cloud.githubusercontent.com/assets/326471/19407318/47c47438-92d1-11e6-82d8-d40e5915b6a4.png)
鼠标移动到某行，会淡黄色背景，选中某个key或value，还会有个更深的背景色

3. 这个可以加上

4. 不同类型的 是有显示提示的
![image](https://cloud.githubusercontent.com/assets/326471/19407316/3ccb9f84-92d1-11e6-9b63-35112c27ec61.png)

**Comment by zozoh** [comment]
1.  不是每次操作哦，只是“添加”|“删除” 这样的操作
         - 同时操作放到菜单上，为什么会怪呢？ 在菜单上没有“添加“ 只有点一个项目展出的菜单才有添加，会，不太熟悉的用户一开始会有一小点蒙圈：“怎么添加键？”
         - 其实添加一个键，似乎更普遍的设计是加一个空行，用户直接按回车就确定了
2. 哦
3. 咋加？ 在菜单上加的话，弹出菜单上的“添加” 就没有必要了吧
4. 我的意思是说，“更明显” 不过这个不重要，现在主要的焦点就是“添加” 是否放在菜单上。

**Comment by zozoh** [comment]
#88
