### ISSUE TITLE
几个主要页面是否可以放开配置

### ISSUE THREAD

**Issue by pangwu86** [zozoh/walnut#9]
主要是页面指
1. 登陆/注册页面
2. 登陆后跳转的首页

walnut里提供默认页面

然后在web.properties里提供2个选项
page-login=~/.../.../xxx_login.jsp
page-home=~/.../.../xxx_login.jsp

**Comment by zozoh** [comment]
1. 这个我正在设计，希望每个用户提供的服务，都能有自己的登录和注册页面。`比如 www.walnut.com` 是访问 *root* 的注册登录界面， `pangwu.walnut.com` 是访问 *pangwu* 这个用户提供的注册/登录界面
2. 实际上，希望在用户的环境变量 `OPEN` 里指定登录后的调整首页

**Comment by pangwu86** [comment]
en, 看到了 关于2, 其实现在就是直接访问/app/open/****  这里的页面本来就是根据app名称打开的, 所以没有所谓的指定到某个页面的必要了

**Comment by pangwu86** [comment]
关于1,  你希望的pangwu.walnut.com 是注册到pangwu这个用户下 ???? 没搞懂

**Comment by zozoh** [comment]
在这个提交（7824b175ab73e466956eebe8bc2e7a8db2994fff) 完成了定制化登录页面的功能

**Comment by zozoh** [comment]
文档 https://github.com/zozoh/walnut/blob/master/doc/core/domain.md 最后一节是描述了定制化登录页面的机制的
